name: NodeJS with Webpack

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello world!"

  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test Job 2
        run: echo "I am the test job 2!"
